<?php

namespace Database\Seeders;

use App\Models\Admin\SectionPart;
use Illuminate\Database\Seeder;

class SectionPartSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $data = $this->data();

        foreach ($data as $value) {
            SectionPart::create([
                'order' => $value['order'],
                'duration' => $value['duration'],
                'part_id' => $value['part_id'],
                'isValid' => $value['isValid'],
                'label' => $value['label'],
                'title' => $value['title'],
                'type' => $value['type'],
                'version' => $value['version'],
                'quest_description' => $value['quest_description'] ?? null,
                'quest_information' => $value['quest_information'] ?? null,
                'quest_title' => $value['quest_title'] ?? null,
                'section_id' => $value['section_id'],
                'soundscape_volume' => $value['soundscape_volume'],
                'part_video' => $value['part_video'] ?? null,
                'part_audio' => $value['part_audio'] ?? null,
                'soundscape_id' => $value['soundscape_id'],
                'program_id' => $value['program_id'],
            ]);
        }
    }


    private function data():array
    {
        return [
            [
                "part_id" =>  "301027-732126",
                "order" =>  1,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Hazırlanmak",
                "title" =>  "Sarkaç Hazırlanması",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "Çakraların ölçümünü için sarkaç hazırlamak için en kolay yöntem\n1- İnce bir iplik alın. Takriben 30-40 cm yeterli.\n2- Herhangi bir boncuk alın ( Cam, metal, plastik, tahta, seramik, olabilir. Boncuğu ipe bağlayın. Sarkacınız hazır. ",
                "quest_information" =>  "Çakraların ölçümü için ön hazırlık.",
                "quest_title" =>  "Sarkaç ( Pandül ) hazırlamak",
                "section_id" =>  "section-371859",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-308129",
                "order" =>  2,
                "duration" =>  319,
                "isValid" =>  true,
                "label" =>  "1. Bölüm",
                "title" =>  "Çakralara Giriş",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-371859",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301027-347382",
                "order" =>  3,
                "duration" =>  1202,
                "isValid" =>  true,
                "label" =>  "2. Bölüm ",
                "title" =>  "Nefes Çalışması - Tepe Çakra",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-371859",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301027-584915",
                "order" =>  4,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Nefes Çalışması",
                "title" =>  "Nefes Çalışmasına Katılabildiniz mi?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "3. Bölümde yer alan nefes çalışmasına katılabildiniz mi?",
                "quest_information" =>  "Nefes çalışmasını uygulamış olanlar, lütfen bu bölümü onaylayın ve devam edin.",
                "quest_title" =>  "Nefes çalışmasını",
                "section_id" =>  "section-371859",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-710729",
                "order" =>  5,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Tepe Çakra",
                "title" =>  "Tepe Çakra Ölçümü",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "Tepe çakranızı sarkacınız ile ölçebildiniz mi? Saat yönünde dönüyorsa lütfen bu bölümü onaylayıp geçin. Ters dönüyorsa nefes çalışmasını lütfen tekrar uygulayın.",
                "quest_information" =>  "Tepe çakranızın dönüş açısı saat yönünde mi?",
                "quest_title" =>  "Tepe Çakra Ölçümü",
                "section_id" =>  "section-371859",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-604151",
                "order" =>  1,
                "duration" =>  1618,
                "isValid" =>  true,
                "label" =>  "3. Bölüm",
                "title" =>  "3. Göz ve Boğaz Çakrası",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301027-391065",
                "order" =>  2,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "3. Göz Çakrası",
                "title" =>  "3. Göz Çakrası Ölçümü",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "3. Göz Çakranızı sarkacınız ile ölçebildiniz mi? Saat yönünde mi dönüyor? Değilse lütfen videolarda yer alan olumlamaları tekrar uygulayınız.",
                "quest_information" =>  "3. Göz çakranız hangi yönde dönüyor?",
                "quest_title" =>  "3. Göz Çakrası Ölçümü",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-344546",
                "order" =>  3,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Boğaz Çakrası",
                "title" =>  "Boğaz Çakrası Enerji Ölçümü",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "Boğaz çakranız hangi yönde dönüyor? Saat yönünde dönüyorsa lütfen bu bölümü onaylayıp diğer bölüme devam ediniz.",
                "quest_information" =>  "Boğaz çakranız hangi yönde dönüyor?",
                "quest_title" =>  "Boğaz Çakrası Enerji Ölçümü",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-646427",
                "order" =>  4,
                "duration" =>  943,
                "isValid" =>  true,
                "label" =>  "4. Bölüm",
                "title" =>  "Kalp - Mide ve Saçral Çakra",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301027-745680",
                "order" =>  5,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Kalp Çakrası",
                "title" =>  "Kalp Çakrası Enerji Ölçümü",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "Kalp Çakranızda enerji ölçümü saat yönünde dönüyorsa, lütfen bu bölümü onaylayıp diğer bölüme devam ediniz.",
                "quest_information" =>  "Kalp çakranız saat yönünde mi dönüyor?",
                "quest_title" =>  "Kalp Çakrası Enerji Ölçümü",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-195672",
                "order" =>  6,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Solar Pleksus Çakra",
                "title" =>  "Solar Pleksus Çakra Enerji Ölçümü",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "Mide (Solar Pleksus) Çakranızda enerji ölçümü saat yönünde dönüyorsa, lütfen bu bölümü onaylayıp diğer bölüme devam ediniz.",
                "quest_information" =>  "Solar Pleksus Çakra Enerji Ölçümü",
                "quest_title" =>  "Solar Pleksus Çakra",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-115775",
                "order" =>  6,
                "duration" =>  1257,
                "isValid" =>  true,
                "label" =>  "5. Bölüm",
                "title" =>  "Kök Çakra, Beden Enerji Ölçümü",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301027-630508",
                "order" =>  8,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Sacral Çakranızda",
                "title" =>  "Sacral Çakranızda enerji ölçümü",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "Sacral Çakranızda enerji ölçümü saat yönünde dönüyorsa, lütfen bu bölümü onaylayıp diğer bölüme devam ediniz.",
                "quest_information" =>  "Sacral Çakranızda enerji ölçümü saat yönünde dönme testi",
                "quest_title" =>  "Sacral Çakranızda enerji",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-346582",
                "order" =>  9,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Kök Çakra Enerjisi",
                "title" =>  "Kök Çakra Enerji Ölçümü",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "Kök Çakranızda enerji ölçümü saat yönünde dönüyorsa, lütfen bu bölümü onaylayıp diğer bölüme devam ediniz.",
                "quest_information" =>  "Kök Çakra Enerji Ölçümü",
                "quest_title" =>  "Kök Çakra Enerji Ölçümü",
                "section_id" =>  "section-124493",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301027-957050",
                "order" =>  1,
                "duration" =>  2434,
                "isValid" =>  true,
                "label" =>  "6. Bölüm",
                "title" =>  "Niyetler",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-764663",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301027-511018",
                "order" =>  2,
                "duration" =>  350,
                "isValid" =>  true,
                "label" =>  "7. Bölüm ",
                "title" =>  "Final",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301027",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-764663",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301028-668676",
                "order" =>  1,
                "duration" =>  201,
                "isValid" =>  true,
                "label" =>  "Tasavvuf Serisi",
                "title" =>  "Tasavvuf ve Farkındalığa giriş",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301028",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-999173",
                "soundscape_id" =>  "601110",
                "soundscape_volume" =>  0.05
            ],
            [
                "part_id" =>  "301028-271934",
                "order" =>  2,
                "duration" =>  1567,
                "isValid" =>  true,
                "label" =>  "Tasavvuf Serisi",
                "title" =>  "Tasavvuf Nedir?",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301028",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-999173",
                "soundscape_id" =>  "601115",
                "soundscape_volume" =>  0.1
            ],
            [
                "part_id" =>  "301028-379882",
                "order" =>  1,
                "duration" =>  1151,
                "isValid" =>  true,
                "label" =>  "Tasavvuf Serisi",
                "title" =>  "Tasavvuf ve İnanç Sistemimiz",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301028",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-519987",
                "soundscape_id" =>  "601115",
                "soundscape_volume" =>  0.1
            ],
            [
                "part_id" =>  "301028-508429",
                "order" =>  2,
                "duration" =>  2424,
                "isValid" =>  true,
                "label" =>  "Tasavvuf Serisi",
                "title" =>  "Aşk, İyi Ahlak ve Vicdan",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301028",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-519987",
                "soundscape_id" =>  "601110",
                "soundscape_volume" =>  0.1
            ],
            [
                "part_id" =>  "301028-242795",
                "order" =>  3,
                "duration" =>  1235,
                "isValid" =>  true,
                "label" =>  "Tasavvuf Serisi",
                "title" =>  "Cahillik, Önyargı ve Kaygı",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301028",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-519987",
                "soundscape_id" =>  "601110",
                "soundscape_volume" =>  0.1
            ],
            [
                "part_id" =>  "301028-144501",
                "order" =>  1,
                "duration" =>  646,
                "isValid" =>  true,
                "label" =>  "Tasavvuf Nefesi",
                "title" =>  "Sufi Nefes Çalışması",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301028",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-159292",
                "soundscape_id" =>  "601110",
                "soundscape_volume" =>  0.1
            ],
            [
                "part_id" =>  "301029-571545",
                "order" =>  1,
                "duration" =>  919,
                "isValid" =>  true,
                "label" =>  "1.Bölüm ",
                "title" =>  "Çakralar 2 Giriş",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-511005",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301029-608231",
                "order" =>  1,
                "duration" =>  701,
                "isValid" =>  true,
                "label" =>  "2.Bölüm",
                "title" =>  "Çakralarımız Yaşam Enerjimizi Nasıl Etkiliyor?",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-423909",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301029-241676",
                "order" =>  2,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Enerji Çalışması",
                "title" =>  "Sen de Enerjinle Tanıştın Mı?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "2.Bölümde yer enerji çalışmasını sen de deneyimledin mi?",
                "quest_information" =>  "Çalışmayı uygulamış olanlar, lütfen bu bölümü onaylayın ve devam edin.",
                "quest_title" =>  "Sen de Enerjinle Tanıştın Mı?",
                "section_id" =>  "section-423909",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301029-786544",
                "order" =>  3,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Nefes Çalışması ",
                "title" =>  "Bizimle Nefes Çalışmasına Katılabildiniz Mi?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "2.Bölümde yer alan nefes çalışmasına katılabildiniz mi?",
                "quest_information" =>  "Nefes çalışmasını uygulamış olanlar, lütfen bu bölümü onaylayın ve devam edin.",
                "quest_title" =>  "Nefes Çalışması",
                "section_id" =>  "section-423909",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301029-738787",
                "order" =>  1,
                "duration" =>  1290,
                "isValid" =>  true,
                "label" =>  "3.Bölüm",
                "title" =>  "Enerji ve Çakraları Ölçme Zamanı",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-132131",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301029-677588",
                "order" =>  2,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Kağıt Çalışması",
                "title" =>  "Kağıt Çalışmasını Sen de  Deneyimledin Mi?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "3.Bölümde yer alan kağıt çalışmasını deneyimleyebildiniz mi?",
                "quest_information" =>  "Kağıt çalışmasını uygulamış olanlar lütfen bu bölümü onaylayın ve devam edin.",
                "quest_title" =>  "Kağıt Çalışmasını..",
                "section_id" =>  "section-132131",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301029-442790",
                "order" =>  1,
                "duration" =>  849,
                "isValid" =>  true,
                "label" =>  "4.Bölüm",
                "title" =>  "Kas Testi ve 3.Göz Çalışması",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-301417",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301029-468530",
                "order" =>  1,
                "duration" =>  722,
                "isValid" =>  true,
                "label" =>  "5.Bölüm",
                "title" =>  "Deneyimler ve Çakra Temizleme",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-190515",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301029-802981",
                "order" =>  1,
                "duration" =>  658,
                "isValid" =>  true,
                "label" =>  "6.Bölüm",
                "title" =>  "Nefes Çalışması ve Kapanış",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301029",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-857668",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-835251",
                "order" =>  1,
                "duration" =>  872,
                "isValid" =>  true,
                "label" =>  "1.Bölüm",
                "title" =>  "Numerolojiye Giriş ve 1 Numaranın Açıklaması",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-590288",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-266319",
                "order" =>  2,
                "duration" =>  1151,
                "isValid" =>  true,
                "label" =>  "2.Bölüm",
                "title" =>  "2 ve 3 Numaranın Açıklaması",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-590288",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-556649",
                "order" =>  3,
                "duration" =>  1194,
                "isValid" =>  true,
                "label" =>  "3.Bölüm",
                "title" =>  "4-5 ve 6 Numaranın Açıklaması",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-590288",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-265364",
                "order" =>  4,
                "duration" =>  1163,
                "isValid" =>  true,
                "label" =>  "4.Bölüm",
                "title" =>  "7-8-9 ve 0 Numaranın Açıklaması",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-590288",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-574554",
                "order" =>  5,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Sayı Çalışması..",
                "title" =>  "Hangi Sayıyla Yakınlık Hissettiniz?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "Siz hesaplama yapmadan hangi sayı ile yakınlık hissettiniz?",
                "quest_information" =>  "Aklınıza gelen sayıyı not aldıktan sonra,lütfen bu bölümü onaylayın ve devam edin.",
                "quest_title" =>  "Sayı Çalışması..",
                "section_id" =>  "section-590288",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301030-228299",
                "order" =>  1,
                "duration" =>  756,
                "isValid" =>  true,
                "label" =>  "5.Bölüm",
                "title" =>  "Numeroloji Heaplamaya Giriş",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-479561",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-697823",
                "order" =>  2,
                "duration" =>  902,
                "isValid" =>  true,
                "label" =>  "6.Bölüm",
                "title" =>  "Numeroloji Hesaplama Detayları",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-479561",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-973118",
                "order" =>  1,
                "duration" =>  1277,
                "isValid" =>  true,
                "label" =>  "7.Bölüm",
                "title" =>  "Eş ile Uyum Numerolojisi",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-359117",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-691084",
                "order" =>  2,
                "duration" =>  991,
                "isValid" =>  true,
                "label" =>  "8.Bölüm",
                "title" =>  "Ebeveyn Numerolojisi",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-359117",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-238632",
                "order" =>  3,
                "duration" =>  795,
                "isValid" =>  true,
                "label" =>  "9.Bölüm",
                "title" =>  "Ebeveyn ve Çocuk Numerolojisi",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-359117",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-598384",
                "order" =>  4,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Ne Fark Ettin?",
                "title" =>  "Bu Hesaplamayla Ne Fark Ettin?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "Bu hesaplamayla ne fark ettin?Sakince bir düşün ve not al lütfen.",
                "quest_information" =>  "Ne fark ettiğinizi not aldıktan sonra, lütfen bu bölümü onaylayın ve devam edin.",
                "quest_title" =>  "Bu Hesaplamayla Ne Fark Ettin?",
                "section_id" =>  "section-359117",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301030-541636",
                "order" =>  5,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Bugünden İtibaren..",
                "title" =>  "Neyi Farklı Yapabilirsin?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "Bu farkındalık ile bu günden itibaren neyi farklı yapabilirsin?",
                "quest_information" =>  "Bu farkındalık ile bu günden itibaren neyi farklı yapabilirsin?Onaylayın ve devam edin..",
                "quest_title" =>  "Bugünden İtibaren..",
                "section_id" =>  "section-359117",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301030-339264",
                "order" =>  1,
                "duration" =>  1086,
                "isValid" =>  true,
                "label" =>  "10.Bölüm",
                "title" =>  "Örnek Uygulamalar",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-608607",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-889757",
                "order" =>  2,
                "duration" =>  907,
                "isValid" =>  true,
                "label" =>  "11.Bölüm",
                "title" =>  "Geliştirici Uygulamalar",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-608607",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301030-100862",
                "order" =>  3,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Örnek Çalışma..",
                "title" =>  "Örnek Çalışma...",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "Siz örnek çalışmanızı kim ile yapmak istiyorsunuz? Ne zaman?",
                "quest_information" =>  "Siz örnek çalışmanızı kim ile yapmak istiyorsunuz? Ne zaman?Devam edin ve onaylayın..",
                "quest_title" =>  "Örnek Çalışma..",
                "section_id" =>  "section-608607",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301030-954108",
                "order" =>  4,
                "duration" =>  626,
                "isValid" =>  true,
                "label" =>  "12.Bölüm",
                "title" =>  "Kapanış",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301030",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-608607",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-729909",
                "order" =>  1,
                "duration" =>  1120,
                "isValid" =>  true,
                "label" =>  "1. Bölüm",
                "title" =>  "Frekansına Göre Eş Bulma",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-984798",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-390191",
                "order" =>  2,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Nefes Çalışması",
                "title" =>  "Nefes çalışmasına katılabildiniz mi?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "1. Bölümde yer alan nefes çalışmasına katılabildiniz mi?",
                "quest_information" =>  "Nefes çalışmasını uygulamış olanlar, bu bölümü onaylayın ve devam edin..",
                "quest_title" =>  "Nefes çalışmasını",
                "section_id" =>  "section-984798",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301031-560562",
                "order" =>  3,
                "duration" =>  1186,
                "isValid" =>  true,
                "label" =>  "2.Bölüm",
                "title" =>  "Kimleri Yargıladın?",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-984798",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-299775",
                "order" =>  4,
                "duration" =>  1205,
                "isValid" =>  true,
                "label" =>  "3.Bölüm",
                "title" =>  "Karşılıksız Sevgi",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-984798",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-559808",
                "order" =>  1,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Nefes Çalışması",
                "title" =>  "Nefes çalışmasına katılabildiniz mi?",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "3. Bölümde yer alan nefes çalışmasına katılabildiniz mi?",
                "quest_information" =>  "Nefes çalışmasını uygulamış olanlar bu bölümü onaylayın ve devam edin.",
                "quest_title" =>  "Nefes çalışmasını",
                "section_id" =>  "section-507826",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301031-635318",
                "order" =>  2,
                "duration" =>  1067,
                "isValid" =>  true,
                "label" =>  "4.Bölüm",
                "title" =>  "Evlilikte Sınavlar",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-507826",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-871738",
                "order" =>  3,
                "duration" =>  1117,
                "isValid" =>  true,
                "label" =>  "5.Bölüm",
                "title" =>  "Aşka Hazır Mısın?",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-507826",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-774028",
                "order" =>  4,
                "duration" =>  1180,
                "isValid" =>  true,
                "label" =>  "6.Bölüm",
                "title" =>  "Doğru Niyetle Eş Seçimi",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-507826",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-301282",
                "order" =>  1,
                "duration" =>  1052,
                "isValid" =>  true,
                "label" =>  "7.Bölüm",
                "title" =>  "Birlikte Yol Almak",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-159702",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-461936",
                "order" =>  2,
                "duration" =>  0,
                "isValid" =>  true,
                "label" =>  "Çizgi Film",
                "title" =>  "\"Eksik Parça\" Çizgi Film",
                "type" =>  "quest",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "7.Bölümdeki \"Eksik parça\" çizgi filmini izlediniz mi?",
                "quest_information" =>  "Eksik parça çizgi filmini izlemiş olanlar, lütfen bu bölümü onaylayın ve devam edin.",
                "quest_title" =>  "\"Eksik Parça\" Çizgi Film",
                "section_id" =>  "section-159702",
                "soundscape_id" =>  null,
                "soundscape_volume" =>  0.15
            ],
            [
                "part_id" =>  "301031-995241",
                "order" =>  3,
                "duration" =>  1218,
                "isValid" =>  true,
                "label" =>  "8.Bölüm",
                "title" =>  "Kendini Geliştirebilir Misin?",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-159702",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-771369",
                "order" =>  4,
                "duration" =>  1238,
                "isValid" =>  true,
                "label" =>  "9.Bölüm",
                "title" =>  "Tam ve Bütünüm",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-159702",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-101944",
                "order" =>  1,
                "duration" =>  1276,
                "isValid" =>  true,
                "label" =>  "10.Bölüm",
                "title" =>  "Nefes Çalışması",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-554946",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ],
            [
                "part_id" =>  "301031-748285",
                "order" =>  2,
                "duration" =>  414,
                "isValid" =>  true,
                "label" =>  "11.Bölüm",
                "title" =>  "Kapanış",
                "type" =>  "video",
                "version" =>  1,
                "program_id" =>  "301031",
                "quest_description" =>  "",
                "quest_information" =>  "",
                "quest_title" =>  "",
                "section_id" =>  "section-554946",
                "soundscape_id" =>  601118,
                "soundscape_volume" =>  0
            ]
        ];
    }
}
