<?php

namespace Database\Seeders;

use App\Models\Admin\TodayPool;
use Illuminate\Database\Seeder;

class TodayPoolSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $data = $this->data();

        foreach ($data as $value) {
            TodayPool::create([
                'content_id' => $value['content_id'],
                'dimension_id' => $value['dimension_id'],
                'section_id' => $value['section_id'],
                'updated_by' => $value['updated_by'],
                'created_by' => $value['created_by'],
            ]);
        }
    }

    private function data():array
    {
        return [
            [
                "content_id" =>  "101200",
                "dimension_id" =>  "music",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101201",
                "dimension_id" =>  "music",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101208",
                "dimension_id" =>  "music",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101205",
                "dimension_id" =>  "music",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101203",
                "dimension_id" =>  "music",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101204",
                "dimension_id" =>  "music",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101073",
                "dimension_id" =>  "family_parenting",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101110",
                "dimension_id" =>  "family_parenting",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101087",
                "dimension_id" =>  "family_parenting",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101084",
                "dimension_id" =>  "family_parenting",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101115",
                "dimension_id" =>  "family_parenting",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101118",
                "dimension_id" =>  "family_parenting",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101102",
                "dimension_id" =>  "occupational",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101089",
                "dimension_id" =>  "occupational",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101128",
                "dimension_id" =>  "occupational",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101112",
                "dimension_id" =>  "occupational",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101287",
                "dimension_id" =>  "occupational",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101166",
                "dimension_id" =>  "occupational",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101073",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101075",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101076",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101109",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101113",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101108",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101189",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101214",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101216",
                "dimension_id" =>  "spiritual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101076",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101098",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101099",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101081",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101127",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101178",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101219",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101187",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101205",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101097",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101100",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101129",
                "dimension_id" =>  "meditation",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101076",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101073",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101074",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101075",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101301",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101300",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101103",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101107",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101143",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101231",
                "dimension_id" =>  "intellectual",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101073",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101074",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101076",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101096",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101084",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101104",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101167",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101086",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101087",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101093",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101165",
                "dimension_id" =>  "relationships",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101101",
                "dimension_id" =>  "sleep",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101128",
                "dimension_id" =>  "sleep",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101179",
                "dimension_id" =>  "sleep",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101187",
                "dimension_id" =>  "sleep",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101203",
                "dimension_id" =>  "sleep",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101204",
                "dimension_id" =>  "sleep",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101208",
                "dimension_id" =>  "sleep",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101283",
                "dimension_id" =>  "sleep",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101082",
                "dimension_id" =>  "physical",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101105",
                "dimension_id" =>  "physical",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101222",
                "dimension_id" =>  "physical",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101278",
                "dimension_id" =>  "physical",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101294",
                "dimension_id" =>  "physical",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101074",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101081",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101085",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101094",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101099",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101114",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101219",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101105",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ],
            [
                "content_id" =>  "101383",
                "dimension_id" =>  "emotional",
                "section_id" =>  "series",
                "created_by" => 801000,
                "updated_by" => 801000,
            ]
        ];
    }
}
